import pandas as pd
import random
from datetime import datetime, timedelta

products_data = [
    {
        'product_id': 'P001',
        'name': 'Samsung 55" 4K Smart TV',
        'category': 'Electronics',
        'subcategory': 'Televisions',
        'brand': 'Samsung',
        'price': 45999,
        'original_price': 65999,
        'rating': 4.5,
        'reviews_count': 1245,
        'stock': 45,
        'description': '55-inch 4K UHD Smart LED TV with HDR and Built-in Alexa',
        'image_url': 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400',
        'features': '4K UHD|Smart TV|HDR|Alexa Built-in|3 HDMI Ports'
    },
    {
        'product_id': 'P002',
        'name': 'LG 260L Frost Free Refrigerator',
        'category': 'Appliances',
        'subcategory': 'Refrigerators',
        'brand': 'LG',
        'price': 23990,
        'original_price': 31990,
        'rating': 4.3,
        'reviews_count': 856,
        'stock': 28,
        'description': 'Double Door Refrigerator with Smart Inverter Compressor',
        'image_url': 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400',
        'features': '260L Capacity|Frost Free|Smart Inverter|Energy Star'
    },
    {
        'product_id': 'P003',
        'name': 'Whirlpool 7.5 Kg Washing Machine',
        'category': 'Appliances',
        'subcategory': 'Washing Machines',
        'brand': 'Whirlpool',
        'price': 18499,
        'original_price': 24999,
        'rating': 4.4,
        'reviews_count': 632,
        'stock': 35,
        'description': 'Fully Automatic Top Load with Hard Water Wash',
        'image_url': 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=400',
        'features': '7.5 Kg|Top Load|Hard Water Wash|Auto Restart'
    },
    {
        'product_id': 'P004',
        'name': 'Sony Noise Cancelling Headphones',
        'category': 'Electronics',
        'subcategory': 'Audio',
        'brand': 'Sony',
        'price': 24990,
        'original_price': 29990,
        'rating': 4.6,
        'reviews_count': 2134,
        'stock': 120,
        'description': 'WH-1000XM4 Wireless Premium Noise Canceling Overhead Headphones',
        'image_url': 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400',
        'features': 'Active Noise Cancellation|30Hr Battery|Touch Controls|Premium Sound'
    },
    {
        'product_id': 'P005',
        'name': 'Apple iPhone 14 Pro',
        'category': 'Electronics',
        'subcategory': 'Smartphones',
        'brand': 'Apple',
        'price': 129900,
        'original_price': 139900,
        'rating': 4.7,
        'reviews_count': 3421,
        'stock': 65,
        'description': '256GB Deep Purple with A16 Bionic Chip',
        'image_url': 'https://images.unsplash.com/photo-1678652197142-d0e7ad93d19d?w=400',
        'features': 'A16 Bionic|256GB Storage|Pro Camera System|Dynamic Island'
    },
    {
        'product_id': 'P006',
        'name': 'Instant Pot Duo 7-in-1',
        'category': 'Appliances',
        'subcategory': 'Kitchen',
        'brand': 'Instant Pot',
        'price': 8999,
        'original_price': 12999,
        'rating': 4.5,
        'reviews_count': 1876,
        'stock': 90,
        'description': 'Electric Pressure Cooker 6L with Multiple Functions',
        'image_url': 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400',
        'features': '7-in-1 Functions|6L Capacity|Stainless Steel|Smart Programs'
    },
    {
        'product_id': 'P007',
        'name': 'Dyson V11 Vacuum Cleaner',
        'category': 'Appliances',
        'subcategory': 'Vacuum Cleaners',
        'brand': 'Dyson',
        'price': 49900,
        'original_price': 59900,
        'rating': 4.6,
        'reviews_count': 945,
        'stock': 42,
        'description': 'Cordless Vacuum with Intelligent Cleaning Mode',
        'image_url': 'https://images.unsplash.com/photo-1558317374-067fb86c6f7e?w=400',
        'features': 'Cordless|60min Runtime|HEPA Filter|LCD Screen'
    },
    {
        'product_id': 'P008',
        'name': 'Dell XPS 15 Laptop',
        'category': 'Electronics',
        'subcategory': 'Laptops',
        'brand': 'Dell',
        'price': 145900,
        'original_price': 165900,
        'rating': 4.5,
        'reviews_count': 1234,
        'stock': 28,
        'description': '15.6" FHD i7 11th Gen 16GB RAM 512GB SSD',
        'image_url': 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
        'features': 'Intel i7|16GB RAM|512GB SSD|NVIDIA GTX 1650|FHD Display'
    },
    {
        'product_id': 'P009',
        'name': 'Philips Air Fryer XXL',
        'category': 'Appliances',
        'subcategory': 'Kitchen',
        'brand': 'Philips',
        'price': 16999,
        'original_price': 22999,
        'rating': 4.4,
        'reviews_count': 2341,
        'stock': 75,
        'description': 'Digital Air Fryer 1.4kg with Rapid Air Technology',
        'image_url': 'https://images.unsplash.com/photo-1585937421612-70e516a76e4e?w=400',
        'features': '1.4kg Capacity|Digital Touch|Dishwasher Safe|7 Presets'
    },
    {
        'product_id': 'P010',
        'name': 'Canon EOS R6 Camera',
        'category': 'Electronics',
        'subcategory': 'Cameras',
        'brand': 'Canon',
        'price': 209900,
        'original_price': 239900,
        'rating': 4.8,
        'reviews_count': 876,
        'stock': 18,
        'description': 'Mirrorless Camera with 24-105mm Lens Kit',
        'image_url': 'https://images.unsplash.com/photo-1606980645935-22a57f8d36ce?w=400',
        'features': '20.1MP|4K Video|In-Body Stabilization|Dual Card Slots'
    },
    {
        'product_id': 'P011',
        'name': 'Breville Barista Express',
        'category': 'Appliances',
        'subcategory': 'Coffee Makers',
        'brand': 'Breville',
        'price': 52990,
        'original_price': 64990,
        'rating': 4.7,
        'reviews_count': 1567,
        'stock': 32,
        'description': 'Espresso Machine with Built-in Grinder',
        'image_url': 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400',
        'features': 'Built-in Grinder|15 Bar Pressure|Milk Frother|PID Temperature'
    },
    {
        'product_id': 'P012',
        'name': 'iPad Pro 12.9" M2 Chip',
        'category': 'Electronics',
        'subcategory': 'Tablets',
        'brand': 'Apple',
        'price': 109900,
        'original_price': 119900,
        'rating': 4.7,
        'reviews_count': 2145,
        'stock': 55,
        'description': '256GB Space Gray with Liquid Retina XDR Display',
        'image_url': 'https://images.unsplash.com/photo-1585790152764-0e155d6e1134?w=400',
        'features': 'M2 Chip|12.9" XDR Display|256GB|5G|Face ID'
    },
    {
        'product_id': 'P013',
        'name': 'Nest Learning Thermostat',
        'category': 'Smart Home',
        'subcategory': 'Climate Control',
        'brand': 'Google Nest',
        'price': 21990,
        'original_price': 26990,
        'rating': 4.4,
        'reviews_count': 756,
        'stock': 68,
        'description': 'Smart WiFi Thermostat with Auto-Schedule',
        'image_url': 'https://images.unsplash.com/photo-1558089687-18d3f697518c?w=400',
        'features': 'Auto-Schedule|Energy Saving|Remote Control|Works with Alexa'
    },
    {
        'product_id': 'P014',
        'name': 'KitchenAid Stand Mixer',
        'category': 'Appliances',
        'subcategory': 'Kitchen',
        'brand': 'KitchenAid',
        'price': 34990,
        'original_price': 44990,
        'rating': 4.8,
        'reviews_count': 3245,
        'stock': 48,
        'description': '5-Quart Tilt-Head Stand Mixer with 10 Speeds',
        'image_url': 'https://images.unsplash.com/photo-1578643463396-0997cb5328c1?w=400',
        'features': '5 Quart Bowl|10 Speeds|Multiple Attachments|Tilt-Head Design'
    },
    {
        'product_id': 'P015',
        'name': 'Ring Video Doorbell Pro 2',
        'category': 'Smart Home',
        'subcategory': 'Security',
        'brand': 'Ring',
        'price': 16999,
        'original_price': 21999,
        'rating': 4.3,
        'reviews_count': 1432,
        'stock': 95,
        'description': 'Smart Doorbell with HD Video and 3D Motion Detection',
        'image_url': 'https://images.unsplash.com/photo-1558002038-1055907df827?w=400',
        'features': 'HD Video|3D Motion|Night Vision|Works with Alexa|Two-Way Talk'
    },
    {
        'product_id': 'P016',
        'name': 'Bose SoundLink Revolve+',
        'category': 'Electronics',
        'subcategory': 'Speakers',
        'brand': 'Bose',
        'price': 22490,
        'original_price': 27990,
        'rating': 4.5,
        'reviews_count': 987,
        'stock': 82,
        'description': 'Portable Bluetooth Speaker with 360° Sound',
        'image_url': 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400',
        'features': '360° Sound|16Hr Battery|Water Resistant|Wireless|Voice Prompts'
    },
    {
        'product_id': 'P017',
        'name': 'Roomba j7+ Robot Vacuum',
        'category': 'Appliances',
        'subcategory': 'Vacuum Cleaners',
        'brand': 'iRobot',
        'price': 69900,
        'original_price': 84900,
        'rating': 4.6,
        'reviews_count': 1765,
        'stock': 38,
        'description': 'Self-Emptying Robot Vacuum with Smart Mapping',
        'image_url': 'https://images.unsplash.com/photo-1558317374-067fb86c6f7e?w=400',
        'features': 'Self-Emptying|Smart Mapping|Obstacle Avoidance|App Control'
    },
    {
        'product_id': 'P018',
        'name': 'Microsoft Surface Pro 9',
        'category': 'Electronics',
        'subcategory': 'Tablets',
        'brand': 'Microsoft',
        'price': 89900,
        'original_price': 99900,
        'rating': 4.4,
        'reviews_count': 1098,
        'stock': 44,
        'description': '13" Touchscreen i5 8GB RAM 256GB SSD',
        'image_url': 'https://images.unsplash.com/photo-1566762928350-b59e4c6548f7?w=400',
        'features': 'Intel i5|8GB RAM|256GB SSD|13" Touch|Windows 11'
    },
    {
        'product_id': 'P019',
        'name': 'Ninja Foodi Multi-Cooker',
        'category': 'Appliances',
        'subcategory': 'Kitchen',
        'brand': 'Ninja',
        'price': 24990,
        'original_price': 32990,
        'rating': 4.5,
        'reviews_count': 2876,
        'stock': 67,
        'description': '9-in-1 Pressure Cooker & Air Fryer 6L',
        'image_url': 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400',
        'features': '9-in-1|Pressure Cook|Air Fry|6L Capacity|Crisping Lid'
    },
    {
        'product_id': 'P020',
        'name': 'GoPro HERO11 Black',
        'category': 'Electronics',
        'subcategory': 'Cameras',
        'brand': 'GoPro',
        'price': 44990,
        'original_price': 54990,
        'rating': 4.6,
        'reviews_count': 1543,
        'stock': 72,
        'description': 'Action Camera with 5.3K Video and Image Stabilization',
        'image_url': 'https://images.unsplash.com/photo-1606980645935-22a57f8d36ce?w=400',
        'features': '5.3K Video|HyperSmooth 5.0|Waterproof|Night Mode|TimeWarp'
    }
]

df = pd.DataFrame(products_data)
df.to_csv('ecommerce_store/data/products.csv', index=False)
print(f"Created product catalog with {len(df)} products")
